services:
    _defaults:
        public: true


    # prestashop.admin.customer_preferences.form_handler:
    doctrineentitiesmodule.admin.module_config.form_handler:
        class: 'DoctrineEntitiesModule\Form\Type\Admin\Configure\ModuleSettingsFormHandler'
        arguments:
            - '@=service("form.factory").createBuilder()'
            - '@prestashop.core.hook.dispatcher'
            - '@doctrineentitiesmodule.admin.module_config.data_provider'
            -
              'doctrineentitiesmoduleConfig': 'DoctrineEntitiesModule\Form\Type\Admin\ModuleConfigType'
            - 'DoctrineEntitiesModuleAdminConfigurationPage'
        # calls:
        #     - method: setTabRepository
        #       arguments:
        #           - '@prestashop.core.admin.tab.repository'

    # prestashop.admin.customer_preferences.data_provider:
    doctrineentitiesmodule.admin.module_config.data_provider:
        class: 'DoctrineEntitiesModule\Form\Type\Admin\Configure\ModuleSettingsDataProvider'
        arguments:
            - '@doctrineentitiesmodule.admin.module_configuration'
            - '@translator'

    # prestashop.adapter.customer.customer_configuration:
    doctrineentitiesmodule.admin.module_configuration:
        class: 'DoctrineEntitiesModule\Form\ModuleConfigurationAdapter'
        arguments:
            - '@prestashop.adapter.legacy.configuration'

    DoctrineEntitiesModule\Entity\ResourceRepository:
        class: DoctrineEntitiesModule\Entity\ResourceRepository
        arguments:
            - "@prestashop.adapter.legacy.context"
            - "@doctrine.orm.entity_manager"

    DoctrineEntitiesModule\Security\Voter\ResourceVoter:
        class:  DoctrineEntitiesModule\Security\Voter\ResourceVoter
        tags:
            - { name: security.voter }
        public: false

    db_prefixer:
        class: DoctrineEntitiesModule\Schema\TablePrefixer
        arguments: ['ps_']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    # prestashop.core.grid.factory.language:
    #     class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    #         - '@prestashop.core.grid.definition.factory.language'
    #         - '@prestashop.core.grid.factory.language_decorator'
    #         - '@prestashop.core.grid.filter.form_factory'

    # prestashop.core.grid.definition.factory.language:
    #     class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\LanguageGridDefinitionFactory'
    #     parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    #     arguments:
    #         - "@=service('router').generate('admin_common_reset_search', {'controller': 'language', 'action': 'index'})"
    #         - "@=service('router').generate('admin_languages_index')"
    #     public: true

    # prestashop.core.grid.factory.language_decorator:
    #     class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\LanguageGridDataFactory'
    #     arguments:
    #         - '@prestashop.core.grid.data.factory.language'
    #         - '@prestashop.adapter.language.language_flag_thumbnail_provider'

    # prestashop.core.grid.data.factory.language:
    #     class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    #     arguments:
    #         - '@prestashop.core.grid.quer_.builder.language_query_builder'
    #         - '@prestashop.core.hook.dispatcher'
    #         - '@prestashop.core.grid.query.doctrine_query_parser'
    #         - 'language'

    # # prestashop.core.grid.factory.category:
    # doctrineentitiesmodule.grid.factory.resource:
    #     class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    #     arguments:
    #         - '@doctrineentitiesmodule.grid.definition.factory.resource'
    #         - '@prestashop.core.grid.data.factory.category_decorator'
    #         - '@prestashop.core.grid.filter.category_form_factory'
    #     calls:
    #       - [setHookDispatcher, ['@prestashop.core.hook.dispatcher']]

    # # prestashop.core.grid.definition.factory.category:
    # doctrineentitiesmodule.grid.definition.factory.resource:
    #     class: 'PrestaShop\PrestaShop\Core\Grid\Definition\Factory\CategoryGridDefinitionFactory'
    #     parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    #     arguments:
    #         - "@=service('router').generate('admin_common_reset_search', {'controller': 'category', 'action': 'index'})"
    #         - "@=service('router').generate('admin_category_listing')"
    #         - '@prestashop.adapter.shop.context'
    #     public: true
